### PR TITLE
PR of a completed task as per TODO: Template10.Services.NetworkService #1479

### PR DESCRIPTION
**Pull request by dg2k**
PR of a completed task as per TODO: Template10.Services.NetworkService #1479

### CODE REVIEW

**Comment by mvermef** [comment]
does adding the *.nuget.props actually work on your fork?

**Comment by dg2k** [comment]
No to your question.

I have just included for .nuget.props and .nuget.targets to be ignored in my PR #1479. I know .nuget.props are annoying but here is a workaround:
Once you're ready for a pull-request, point to Team Explorer tab to view Changes, delete [added] ignorables (.targets, .props) and Undo modified ones. In effect, the only changes will be your files and the project file .csproj (unless you amended others). Hope this makes sense.

**Comment by mvermef** [comment]
yea it does but been pulling what hair I have left out trying to wrap my head around the digital malfunction called gitignore not ignoring the set ignore :P

**Comment by dg2k** [comment]
To re-submit due to merge conflict.

**Pull request closed without merging**
