### PR TITLE
Adding DataContext Unwrap Extensibility

### PR DESCRIPTION
**Pull request by 1iveowl**
Enhancement: Enable Navigation Service to cope with wrapped Viewmodels #587

### CODE REVIEW

**Comment by JerryNixon** [comment]
I think the same result can be accomplished using ResolveForPage(). No?

**Comment by 1iveowl** [comment]
Not sure. I have to admit I don't know how to utilize ReSolveForPage(). Is there an sample I can look at somewhere? I'm using MVVM and IOC for my viewmodels.

**Comment by JerryNixon** [comment]
Just look what it does.

``` csharp
// Bootstrapper.cs
public virtual Services.NavigationService.INavigable ResolveForPage(Type page, NavigationService navigationService) => null;

// Navigationservice.cs (NavigateToAsync)
if (page.DataContext == null)
{
    // to support dependency injection, but keeping it optional.
    var viewmodel = BootStrapper.Current.ResolveForPage(page.GetType(), this);
    if (viewmodel != null)
        page.DataContext = viewmodel;
}
```

Accomplishes the same thing you are wanting.

**Comment by 1iveowl** [comment]
Thanks Jerry. I've had some time to look at it and ResolveForPage is only called if the DataContext is null. When using IoC and a wrapped ViewModel, then DataContext is not null. 

What if we change the if-statement to?:

`if (!(page.DataContext is INavigable))`

Then I could override the ResolveForPage, which I think is what you are suggesting and would makes sense as well as be a move elegant solution. 

What do you think?

**Comment by JerryNixon** [comment]
Crazy. Okay. I changed it to `if (!(page.DataContext is INavigable) | page.DataContext == null)`. It's one of those changes that nobody will notice but you, dude!

**Comment by 1iveowl** [comment]
Thank you Jerry. I appreciate it. 

I made a pull request as the current version only covers NavigationTo and not NavigationFrom. I've added code to cover this. Also, I'm raising an event in the case that the Resolver is unable to find a ViewModel. Not sure if that is how you would like it to be? I'm flexible on that one :-)

Regarding others needing this you might be right. Only, time will tell, byt to me the new code looks nicer and more precise now :-)

**Pull request closed without merging**
