### PR TITLE
Hide the Hamburger Menu

### PR DESCRIPTION
**Pull request by ghost**
Add property to hide the menu completely, useful to show full-screen content like a video player.

### CODE REVIEW

**Comment by JerryNixon** [comment]
Great idea.

**Comment by JerryNixon** [comment]
I have implemented HamburgerMenu.IsFullScreen.

**Comment by SBortz** [comment]
You´re awesome :)
The new title bar broke our solution to this.

**Comment by JerryNixon** [comment]
Thanks. How?

Best regards,
Jerry Nixon

Sent from my Windows Phone.
Please forgive typos and brevity.

**Comment by SBortz** [comment]
Not important. We were following a different approach with another parent Grid with 2 VisualStates. Your solution looks great, tomorrow i will have a closer look to it.

**Comment by teamneusta** [comment]
Jerry, I come back to this issue - I get a COM exception when setting IsFullScreen to true. I was able to fix this by adding a missing =null assignment, but the IsFullScreen property has no effect at all. I will file a new issue on this.

**Pull request closed without merging**
