### PR TITLE
Repaired sources uri for control themes

### PR DESCRIPTION
**Pull request by jp-weber**
Controls could not be load because the sources cannot be found => fix sources.

### CODE REVIEW

**Comment by JerryNixon** [comment]
This is a platform change, and I greatly appreciate the update.

**Comment by JerryNixon** [comment]
Can you update this in the 13b branch instead?

**Comment by JerryNixon** [comment]
I will also update these in master, yes.

**Comment by jp-weber** [comment]
Isn't the source correct? 
https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Template10%20(Library).csproj#L11
The assembly name is Template10Library:
https://github.com/Windows-XAML/Template10/blob/version_1.1.13p/Template10%20(Library)/Themes/Generic.xaml

**Pull request merged**
