### PR TITLE
Connected Animation Sample (from issue: #1529)

### PR DESCRIPTION
**Pull request by ImCarrot**
A quick sample for working with connected animations using Template 10

### CODE REVIEW

**Comment by JerryNixon** [comment]
Ouch, needs a little work

**Comment by JerryNixon** [comment]
I cannot merge this, too many conflicts

**Comment by JerryNixon** [comment]
Fix this! I want it!

**Comment by JerryNixon** [comment]
Wow 1,173 file changes. I can never review that.

**Comment by ImCarrot** [comment]
good lord! What just happened overnight? lol I just added 10-20 odd files that's it. How'd that 1,173 file changes happen? Did I pick a wrong branch for a pull request?

**Comment by JerryNixon** [comment]
Thanks

**Pull request closed without merging**
