### PR TITLE
Easy start with VisualStates in MessageDetailTemplate

### PR DESCRIPTION
**Pull request by Greywing**

### CODE REVIEW

**Comment by JerryNixon** [comment]
Help me out. What are you accomplishing with this PR?

**Comment by Greywing** [comment]
I have spent some time to figure out how add VisualState in Data template.
It didnt work without wrapping DataTemplate inside a UserControl

Hope it will help some beginners like me

**Comment by JerryNixon** [comment]
But what problem are you solving with this PR?

**Comment by Greywing** [comment]
Ease of use of this example, I think.
But I get your point of view.

I close it, sorry :)

**Pull request closed without merging**
