### PR TITLE
AwaitableDelegateCommand added. can execute with a key and can be awaited by that key.

### PR DESCRIPTION
**Pull request by waynebaby**
A awaitable command  that can awaited by code by execution key string

### CODE REVIEW

**Comment by JerryNixon** [comment]
Show me the usage syntax.

**Comment by waynebaby** [comment]
``` csharp
    public class VMMock
    {
        public VMMock()
        {


            MyAwaitableCommand = new AwaitableDelegateCommand(
                async cmdParameter =>
                {
                    await Task.Yield(); //<-- some async work 
                },
                cmdParameter => !IsBusy);

        }
        public bool IsBusy { get; set; }

        public AwaitableDelegateCommand MyAwaitableCommand { get; set; }


        public async Task Run3TimesInARow()
        {
            var commandParams = new[] { "exe1", "exe2", "exe3" }
            .Select(x=>new AwaitableDelegateCommandParameter { InnerCommandExecutionParameter ="whatever", ExecutionKey=x})
            .ToArray();

            foreach (var param in commandParams)
            {
                MyAwaitableCommand.Execute(param);
                await MyAwaitableCommand.AwaitByKey(param.ExecutionKey);
            }   //<--  can execute multiple commands in a row  and  use async/await avoid block ui thread.

        }
    }
```

**Comment by waynebaby** [comment]
And the AwaitableDelegateCommandParameter can be contained in  a  resource dictionary to get datacontext and  bind  "ExecutinKey"  and "InnerCommandExecutionParameter"  to datacontext

**Comment by waynebaby** [comment]
The problem in simple ICommand  and delegate implementation is  "Execute" leave no awaitables in return, the delegate is  void (object)  means  you can only waited in ui thread and this will kill your UX if you want to run long-life executing  combined command (Prism ->CombinedCommand).

if we use command like this, can solve the problem.  If you have mind in syntax please improve it.

**Comment by JerryNixon** [comment]
Seems like this syntax would be easier, no?

``` csharp
Task ExecuteAsync(T obj);
```

**Comment by waynebaby** [comment]
sure it could be `Task ExecuteAsync(T obj);`  I will add that. 

but await by key is still needed if the ui fired the command and await is called in VM.

**Comment by JerryNixon** [comment]
I don't know.

**Pull request closed without merging**
