### PR TITLE
Fixing up the valiation

### PR DESCRIPTION
**Pull request by ArtjomP**
Nuget package Panteam.Template10.Validation has been created

### CODE REVIEW

**Comment by JerryNixon** [comment]
Why are you upgrading to 5.2.2?

**Comment by JerryNixon** [comment]
Could you please verify that a ValidationModelBase can be serialized and de-serialized without any problem? If so, I will take your changes and push up Template10.Validation to NuGet so it can be official. What do you think about that?

**Comment by mvermef** [comment]
5.2.2 had some necessary core updates that rtm was lacking, I believe.

[clicky](https://social.msdn.microsoft.com/Forums/en-US/e766a904-7346-4f76-bad2-852d3b301b0e/known-issue-version-52-of-microsoftnetcoreuniversalwindowsplatform-delisted-all?forum=Win10SDKToolsIssues)

**Comment by ArtjomP** [comment]
No, ValidatableViewModelBase is not serializable at this moment. I'll fix it.

**Comment by JerryNixon** [comment]
That's important. Once we have it, I will push it Nuget.

**Pull request closed without merging**
