### PR TITLE
improvements in ObservableItemCollection

### PR DESCRIPTION
**Pull request by aline-almeida**
-add new constructor
-improve ItemPropertyChanged to allow knowing which property changed
-remove handler on clearItems

### CODE REVIEW

**Comment by JerryNixon** [comment]
Why make hamburger disposable?

**Comment by aline-almeida** [comment]
You're right, it doesn't have to be. I've changed that.

**Comment by JerryNixon** [comment]
I think we should add ChangedItemIndex.

**Comment by JerryNixon** [comment]
Do you like ItemChanged or ChangedItem?

**Comment by JerryNixon** [comment]
I like ChangedItem.

**Comment by aline-almeida** [comment]
ChangedItem sounds better!

**Comment by JerryNixon** [comment]
Can we add ChangedItemIndex ?

**Comment by aline-almeida** [comment]
I've already done that.

**Pull request merged**
