### PR TITLE
Add RateApp command and widget 

### PR DESCRIPTION
**Pull request by dkackman**
Added a command to the `SettingsPageViewModel`that will open the app in the windows app store, and a little thumbs up "Rate our app" widget on the about tab of the `SettingsPage`.

### CODE REVIEW

**Comment by JerryNixon** [comment]
I will not be merging this. But, instead, I would like you to submit a MarketplaceService to the library. Something that handles this a few more common scenarios.
1. Nag the user with a popup to rate after N launches.
2. Nag the user with a popup to rate after N days (after install).
3. Manually nag the user to rate the app.
4. Manually launch the store, filtered to the current app.
5. Manually launch the store, filtered to the current publisher. 

Maybe the API is something like this:
1. `MarketplaceService.NagAfterLaunches(10);`
2. `MarketplaceService.NagAfterDays(10);`
3. `MarketplaceService.NagTemplate = myTemplate;`
4. `MarketplaceService.ShowNag();`
5. `MarketplaceService.ShowInStore();`
6. `MarketplaceService.ShowPublisherInStore();`

I am open to API changes, for sure. If you want to take this on, please open an Issue on the GitHub site so we can track the status. When you submit a PR, please do not initially include a Sample project so we can evaluate the API, etc. first. I just want to save you some heartache. 

Make sense?

**Comment by dkackman** [comment]
Does make sense. Let me poke around your codebase some and see if I have any questions about fitting that into your overall structure, style etc.

Above you say "please do **_not_** initially include a Sample project". Was the "not" a typo?

**Comment by darenm** [comment]
The "not" was not a typo - including a sample app increases the size of the pull request to be reviewed. So initially, just submit a pull request with your proposed API changes, etc. It is much easier to review the API and then, if it is accepted (or revised until accepted), a sample can be submitted separately.

**Comment by dkackman** [comment]
Gotcha. 

I've got a couple questions about code organization and fitting this into the design patterns y'all have established. Are those best posed in this thread or someplace else? I can open a GitHub issue on this topic and pose questions there. Just want to fit this into your pre-established patterns and design.

**Pull request closed without merging**
