### PR TITLE
Completed Template10.Services.SerializationService (#1477)

### PR DESCRIPTION
**Pull request by callummoffat**
This PR includes the following changes:

- Updates the folder structure for the SerializationService to the one requested by @JerryNixon
- Added a barebones sample demonstrating the SerializationService
- Created a NuGet package for the SerializationService library
- Added the wiki docs on the SerializationService to the readme.md

### CODE REVIEW

**Comment by mitchcapper** [comment]
There are a lot of local path changes in the nuget.props files can we roll these back except for the versioning to make for a cleaner commit?

**Comment by callummoffat** [comment]
Can do.

Sent from Mail for Windows 10

**Comment by callummoffat** [comment]
@mitchcapper I'm not entirely sure how to go about this.

**Comment by mitchcapper** [comment]
If the tool version upgrade is not required you could just revert those files back  (or really just leave them changed but unstaged on your local machine).  It is the `ProjectAssetsFile` and `NuGetPackageFolders` mainly.

**Comment by JerryNixon** [comment]
Nice

**Comment by callummoffat** [comment]
So, Jerry - you think this is ready to merge?

**Comment by JerryNixon** [comment]
Thanks for your contribution. Closes #1477

**Pull request merged**
