### PR TITLE
Hamburger Menu Custom Styling

### PR DESCRIPTION
**Pull request by vivekhnz**
I've added support for specifying a custom hamburger button style and a custom nav button control template so that developers have greater control over the hamburger menu's visuals.

I've also added brushes for checked+hover and checked+pressed states to the hamburger menu so the hover and pressed colors can be different for the checked state v.s. the unchecked state.

### CODE REVIEW

**Comment by JerryNixon** [comment]
This is nice. Will take a while to review. Like the initial look tho.

**Comment by vivekhnz** [comment]
Great! Let me know if you have any questions.

**Comment by elysium-studio** [comment]
Would be cool to see this pull request get accepted. Really missing Checked+Hover and Checked+Pressed background brushes.

**Comment by dg2k** [comment]
One style name definition missing from the list so far is **NavButtonHoverForeground** and may be take this opportunity to include it. Not a big loss but just for completeness.

**Comment by JerryNixon** [comment]
@vivekhnz can you update your PR per @dg2k's comment above?

**Comment by JerryNixon** [comment]
@vivekhnz I would appreciate it if you would review PR #781 in light of this PR. Would you be interested in integrating the two in a single PR?

**Comment by rcbevans** [comment]
I'd be happy to work with @vivekhnz to pull the PRs together so we can get them merged in.  It may be easiest if I pull these changes across into my PR as it's somewhat smaller than mine is.

Any other feedback on #781 would be great

**Comment by rcbevans** [comment]
I have merged this PR into mine, which has now been updated.  I will try and do some testing and make sure everything is still working as expected

**Comment by JerryNixon** [comment]
Good. Go ahead and fort it and invite him to collaborate, please.

**Pull request closed without merging**
