### PR TITLE
Add custom methods to serialize/deserialize for PageParam data

### PR DESCRIPTION
**Pull request by schuettecarsten**
This pull requests adds two additional methods to NavigationService to serialize and deserialize CurrentPageParam object into strings. These methods only call ToString() in default implementation, if custom behavior is neccessary, you can create a descendent class of NavigationService and extend it in your project.

To make it possible to use a custom NavigationService, I've also added a simply factory method to Bootstrapper.cs which can also be overridden in custom App.xaml.cs class to create a custom NavigationService.

Third, I've added a Task.Yield().GetAwaiter().GetResult() call while wating for Frame.Content to become available on resume. There has been a while(...) {} statement, which eats up CPU while waiting, a yield is better here.

For code cleanup, I also changed several NavigationService to INavigationService in Bootstrapper and Shell.xaml.cs.

### CODE REVIEW

**Comment by schuettecarsten** [comment]
This will also solve https://github.com/Windows-XAML/Template10/issues/280

**Comment by schuettecarsten** [comment]
Additional commits to allow descendant classes of NavigationService: Make constructor "protected internal".

**Comment by schuettecarsten** [comment]
Now it works :)

**Comment by JerryNixon** [comment]
So, this is a breaking change since it invalidates INavigationService. I am also not 100% sure this implementation is better than requiring the developer to add it to the logic of their page instead. That being said, I am going to move this to a next version T10 milestone where we can review it and include it there. You will not see it included in this weeks NuGet update to 1.0.9.

**Comment by schuettecarsten** [comment]
It should not be a breaking change, behavior of existing applications is not changed.

Please note that it is not possible to implement custom serialization behavior with the curretn implementation. Assigning an object to state["name"] throws an exception for complex object and does not call ToString(). state[] is only able to handle strings internally.

**Comment by JerryNixon** [comment]
Where are there both CreateNavigationService and NavigationServiceFactory?

**Comment by schuettecarsten** [comment]
Sorry, closed this accidentially.

**Comment by schuettecarsten** [comment]
To answer your question: I need the method to only create the instance of NavigationService descendant class in my code. The NavigationServiceFActory method cannot be overridden because it contains too much stuff. So I moved only the "new NavigationService(..." into a separate method that can be used to create your own navigation service implementation

**Comment by schuettecarsten** [comment]
Should be mergeable without conflicts

**Pull request closed without merging**
