### PR TITLE
Added JumpListItem to BootStrapper.AdditionalKinds

### PR DESCRIPTION
**Pull request by FrayxRulez**
Added support for `Launching` via `JumpListItem` (API coming with TH2 SDK on November 30)

### CODE REVIEW

**Comment by JerryNixon** [comment]
What you mean jump list item?

**Comment by FrayxRulez** [comment]
This:
imgur

Documentation available here: https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.startscreen.jumplistitem.aspx

When launching the app by clicking them it's like from a secondary tile, but tile id is "App"

**Comment by FrayxRulez** [comment]
I've also added an overload of `NavigationServiceFactory` that allows the dev to specify the frame to be used to create `NavigationService` and `FrameFacade`.

In addition I've added a `virtual CreateRootFrame` method that allows the dev to create a specific frame for default `NavigationService`.

These changes are to solve this issue: https://github.com/Windows-XAML/Template10/issues/346

If you want I can create a sample too!

**Comment by JerryNixon** [comment]
I am not sure why this is necessary? Why not treat it like Primary?

**Comment by JerryNixon** [comment]
For anyone reading this, this is new to 10586

**Pull request merged**
