### PR TITLE
MasterDetailsView control addition

### PR DESCRIPTION
**Pull request by artfuldev**
Since the Master-Details is a very common pattern, I have introduced a `MasterDetailsView` control that derives from a `ListView` but is able to show a Details Pane to the right.

Currently,
- The control automatically occupies maximum available space
- Master Pane Column Width is 400epx
- Details Pane occupies the rest of the space
  - In mobile, only one pane is shown at a time
- Supports progress indicators for the data in both master and details panes
- Supports CommandBars on top for both master and details panes,
  - CommandBars can have content and commands
  - In mobile, the CommandBars with content stay on top, another CommadBar with the commands appear in the bottom for easy access
- Supports back button which appears by default in details pane
- Support for Master Pane Width (this can currently be done by modifying the ControlTemplate)
- Support for minimum width for Narrrow and Normal Visual States

Planning to add,
- Secondary Commands
- Option to show bottom command bar for both panes, with commands and content, which will not be affected on mobile devices
- Option to hide Back Button optionally, but control Hardware Back Button behavior in Details view
- Option to hide Top CommandBars optionally in case of absence of both commands and content, especially for mobile.
- Option to add spacers to accommodate hamburger menu in top CommandBars if necessary

I have edited the existing MasterDetails sample project to include a version with this control. I hope this helps people save time in their projects. :)

### CODE REVIEW

**Comment by kenshinthebattosai** [comment]
## Desktop View:
On The Desktop
## Mobile Master Pane:
Mobile Master Pane
## Mobile Details Pane:
Mobile Details Pane

**Comment by artfuldev** [comment]
The switch button added in the sample is used to switch between the MainPage and the MasterDetailsControlPage

**Comment by sibbl** [comment]
I'd love to see a solution vor master details view in Template10 and like your approach a lot!

There are some `<x:String>Sample</x:String>` in your MainPage.xaml and the `sln` file was changed (removed snippets etc.) - I don't know if this was intended?

**Comment by artfuldev** [comment]
Gosh! Didn't notice the changes to the `.sln` file. These are unintentional. Any help to undo the changes to the `.sln` file much appreciated.

The `<x:String>Sample</x:String>`s are just to have a design time experience without Design Time Data.

**Comment by JerryNixon** [comment]
@kenshinthebattosai, could you please submit this as a sample and not part of the library?

**Comment by artfuldev** [comment]
I thought a Master-Details View control would be nice in Template10... Many people might find it useful. Are samples part of the Nuget Package? I will remove the code from the libary project if you think it's not a good addition to the library. Can you please take another look?

**Comment by sibbl** [comment]
May I ask where you draw the line between samples and controls, @JerryNixon? I used Template10 in 2 projects and in both I fiddled around with copying scripts from the samples to get what I want in my project. I mean the project even has "template" in its name, not "sample collection" and I'd be happy if the control could simply be updated by updating the library (bugfixes, better UI patterns, ...). If it was just in a sample, I could also start with Microsoft's sample from their UWP sample project here on GitHub. It just makes things harder for users. Personally, I see this master-detail view control on the same level as the hamburger menu, which is already a control.

**Comment by robertmuehsig** [comment]
I would also like to see this as a control inside the actual NuGet package.
Besides that it was a bit suprising for me that all those nice Services, sitting inside the [repo](https://github.com/Windows-XAML/Template10/tree/master/Template10%20%28Services%29) are not part of the NuGet package - so I need to copy the whole stuff, which feels wrong.

**Comment by JerryNixon** [comment]
Thanks, guys. This is great feedback. Don't read into this. I like the work and the control. Just want it as a sample for now. I hope you understand.

**Comment by artfuldev** [comment]
Thanks for the support, guys! :+1:
This is about to be my first contribution (of hopefully many in the future) and it's a nice feeling.

@JerryNixon I will update this pull request based on your comments, thanks.

**Comment by sibbl** [comment]
@JerryNixon thanks for the quick response! I was just asking as it might make future pull requests a lot easier if we knew exactly where to draw the line between library controls and samples. 

Btw, what about moving such controls into own projects/Nuget packages, which then extend Template10? Like I said, I'd really love to have a Nuget package I could simply update as this is the whole point of package managers. Would this maybe be an option as well?

**Comment by artfuldev** [comment]
Yes, separate packages which extend Template10 seem to be a good idea to me... But then direct contributions to Template10 will enrich it and will undoubtedly reach a wider audience.

**Comment by JerryNixon** [comment]
In this PR you are adding two converters that are already part of the library using ValueWhen converter. You are also adding a trigger. I don't intend to include triggers. I intend to ship WindowsStateTriggers Nuget with T10. So go ahead and add that to your sample. Please remove the trigger and the converters from the Library. We do not need them.

**Comment by artfuldev** [comment]
Yes, I'll update shortly, thanks. The two converters have more logic than a simple "ValueWhen" converter, because they work for lists (empty). Please enlighten me how to accomplish the same using ValueWhenConverter, if that is indeed possible. It will help.

**Comment by artfuldev** [comment]
Do you mean [this](https://github.com/dotMorten/WindowsStateTriggers)?

**Comment by artfuldev** [comment]
@JerryNixon  all done, take a look :)

**Comment by JerryNixon** [comment]
Cool, Hey. I think you need to undo your changes to generic.xaml, too, in the Library.

**Comment by artfuldev** [comment]
I'll pull from master once more and do these changes. Sorry I'm kind of a rookie at this. :)

**Comment by JerryNixon** [comment]
Well, we're not there yet.
- [ ] Remove your changes about /Converters/Themes/Generic.xaml as this is requiring an update to csproj in the library and I don't want you to do that. Moreover, this was corrected many commits ago.
- [ ] Remove your changes to /Themes/Generic.xaml as these changes are only aesthetic changes introduced by your XAML styling tool. I don't want to parse changes to Generic.xaml, pls

**Comment by artfuldev** [comment]
Will do, thanks

**Comment by artfuldev** [comment]
I'm taking the RAW version of Generic.xaml from the master branch of Windows-XAML/Template10 and pasting it in my file to overwrite its contents. Yet the diff shows I've changed many lines in Generic.xaml. How can this be? Please help

**Comment by artfuldev** [comment]
Fixed that by pulling from master again. I think I've checked both your checkboxes now. Please check and let me know.

**Comment by JerryNixon** [comment]
So long as `Template10 (Library)/Themes/Generic.xaml` is in your PR, I will not merge it into the solution. I hope you understand.

**Comment by sibbl** [comment]
@kenshinthebattosai reverting the `Generic.xaml` to the revision which you forked Template10 should fix this.

**Comment by artfuldev** [comment]
I didn't know how to revert a single file to a version. :(

Somehow I have removed any and all changes I've made to the Library project folders and constrained my changes to the `Samples/MasterDetail` folders. I hope that's what was meant for me to do. Is this alright?

**Comment by sibbl** [comment]
Looks good to me now, at least GitHub doesn't include the Generics.xaml in the unified "files changed" tab of this PR.

**Comment by artfuldev** [comment]
Any update on this, please?

**Comment by DanTheManSWE** [comment]
Why not commit it as a new sample instead of overwriting the current MasterDetail sample?

**Comment by artfuldev** [comment]
@DanTheManSWE The ideas were one and the same, what was different was just an implementation detail, so I imagined they belonged together. Initially I thought the control would become part of the library and replace the existing sample. Also, I haven't overwritten anything, I just added a switch button and a separate page for the new implementation.

**Comment by artfuldev** [comment]
@JerryNixon It's gonna be three weeks now. Any updates, please? At least tell me if there's something more to fix.

**Comment by artfuldev** [comment]
@danthemanswe I did change some namespaces because I thought it was a mistake. All samples had a Messaging namespace then...

**Comment by artfuldev** [comment]
@JerryNixon anything?

**Comment by JerryNixon** [comment]
I would like to see this as an alternate approach. The current behavior-based approach is VERY educational to developers who do not know how to use them in a sophisticated way. Perhaps we create a MasterDetails2 sample with a unique readme.md explaining why it is clever.

**Comment by artfuldev** [comment]
I'm at a loss to know how to proceed. Do you mean I should undo changes to this project and submit as a new sample? I especially do not understand the readme file part. The readme is required for my submission or the existing one?

**Comment by JerryNixon** [comment]
Reflecting on @DanTheManSWE  who was asking why we would overwrite the existing sample. Made me realize the value of the current sample. But, that is to say, your sample is also very valuable to any developer considering the Master/Detail pattern. Let me ask you. How could we include both?

**Comment by artfuldev** [comment]
Again, I'm clarifying. I haven't removed anything from the current sample. Please have a look. You could clone this branch in my fork, for example, and run the sample. I added screenshots to be clear, but I guess they were removed. I have just added one more page, with the new control, and added a switch button to the original sample, which will let you switch between the two approaches, to see how they look and work (extremely similarly, because we even use the same DataTemplates and ViewModels).

This I imagined, at the time, to be a nice way to introduce developers to the logic (via the original sample - how it is done), and a control to make their development easier. In fact, the control makes use of the same behaviour-based approach in many places, only changing where necessary. In the control, we can keep adding additional features, is what I thought.

Do you feel that having two pages, for the same pattern, in the same project, is confusing? I thought it could help them understand the usefulness of a control for something like this.

PS: You also have to know that I initially thought, when made well, this control could make its way into the library. It is, after all, a templated control that can be customized to anyone's liking.

**Pull request merged**
