### PR TITLE
Additional Converters and Sample Project

### PR DESCRIPTION
**Pull request by seesharprun**
Added Sample Project showing how the Converters work

Added two new Converters (DateTimeOffset and NumberFormat)

Will update Wiki page if PR is approved.  The current Wiki page only describes 2/3 existing converters.

### CODE REVIEW

**Comment by MichaelPetrinolis** [comment]
Hi, we could replace the NumberFormat and the DateTimeFormat with something general like the following

```
    public sealed class StringFormatConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, string language)
        {
            string format = (parameter as string) ?? Format;
            if (format == null)
                return value;
            return string.Format(format, value);
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            throw new NotImplementedException();
        }

        public string Format { get; set; }
    }
```

and in app.xaml we could define converters this way in order to mimic the StringFormat of WPF binding

```
            <converters:StringFormatConverter x:Key="StringFormatConverter"/>

            <converters:StringFormatConverter x:Key="DateFormatConverter">
                <converters:StringFormatConverter.Format>
                    <x:String>{0:d}</x:String>
                </converters:StringFormatConverter.Format>
            </converters:StringFormatConverter>

            <converters:StringFormatConverter x:Key="PriceFormatConverter">
                <converters:StringFormatConverter.Format>
                    <x:String>{0:N4}</x:String>
                </converters:StringFormatConverter.Format>
            </converters:StringFormatConverter>

            <converters:StringFormatConverter x:Key="ValueFormatConverter">
                <converters:StringFormatConverter.Format>
                    <x:String>{0:N2}</x:String>
                </converters:StringFormatConverter.Format>
            </converters:StringFormatConverter>
```

like @JerryNixon  has done in the super ValueWhenConverter.

**Comment by JerryNixon** [comment]
Very good.

**Comment by seesharprun** [comment]
I agree with @MichaelPetrinolis, I can do this in a few days.

**Comment by JerryNixon** [comment]
Replace them and update the sample, thanks. And PLEASE include a readme.md in the root of the sample. Thank you.

**Comment by JerryNixon** [comment]
Please try to get this in before the next NuGet push next week.

**Comment by seesharprun** [comment]
No problem, there is some initial documentation but I will try and sync the new documentation and new converters.  I'll see if I can get this in by Friday.  What would be the best way to get requests for more converters before Friday?  I don't know if an Issue is appropriate for that.

**Pull request merged**
