### PR TITLE
Example of a ViewModel resolver

### PR DESCRIPTION
**Pull request by rpedretti**

### CODE REVIEW

**Comment by JerryNixon** [comment]
The app can register view-models in `OnInitializeAsync()` and should inherit from `MvvmLightBootStrapper` and not `BootStrapperBase`. Ack! Obviously an unclear API there. Quite different from T10.1. I need to build out Minimal, maybe with a "Typical" template. I think maybe a `DefaultBootStrapper` might also make sense, later. Hmm. Thoughts?

**Comment by rpedretti** [comment]
I agree on the ```OnInitializeAsync()```. But inheriting from ```MvvmLightBootStrapper``` won't let me choose my DI container. I've build the ```DefaultBootStrapper``` and it Works, but maybe it's not the ideal approach, at least not with this name. I've made the dependency registration a three step action

```
public BootStrapperBase(IContainerService containerService)
{
    // start
    Current = this;
    Services.Container.ContainerService.Default = containerService;
    RegisterMessagingService();
    RegisterInternalDependencies();
    RegisterDependencies();
    .......

public abstract void RegisterMessagingService();
public abstract void RegisterInternalDependencies();
public virtual void RegisterDependencies() { }

....
```


At the abstract ```DefaultBootStrapper``` i've implemented ```RegisterInternalDependencies()``` as it was on the MvvmLight ```RegisterDependencies()```, except the messaging system, wich need to be registered like:
```
public override void RegisterMessagingService()
{
    ContainerService.Register<IMessengerService, MvvmLightMessengerService>();
}
```

I made like this so the ```DefaultBootStrapper```  won't have any reference to the actual messaing implementation.

**Comment by JerryNixon** [comment]
You're right. Let me resolve this somehow.

**Comment by rpedretti** [comment]
Ok. Tell me if there is something I can help with.

**Comment by JerryNixon** [comment]
I will build this for you. In the new Template.Advanced.

**Comment by rpedretti** [comment]
Ok! I don't know if you faced a navigation problem while navigating back, but the current NavigationService won't resolve ViewModels and there will be NullReferences everywhere, unless pages are cached.

**Comment by rpedretti** [comment]
Just saw the updated code at master, ignore me

**Pull request closed without merging**
