### PR TITLE
fixes issue #385 with secondary commands

### PR DESCRIPTION
**Pull request by MichaelPetrinolis**
Modified the template to fix the problems discussed at #385

### CODE REVIEW

**Comment by JerryNixon** [comment]
Please update all `DiscreteObjectKeyFrame` animations to VisualState.Setters/Setter instead. The reason is not just because it is more readable, but also because of performance. Spinning up a Storyboard for this type of work is needless overhead, esp when there is a lot of them.

**Comment by MichaelPetrinolis** [comment]
Sure, the reason I used the storyboards was that the commandbar works as expected and the default template use storyboards. I will try to use setters instead.

**Comment by MichaelPetrinolis** [comment]
It seems that using a setter for the Rect of the OverflowContentRootClip causes this behavior.
I could leave only the OverflowContentRootClip on an ObjectAnimationUsingKeyFrames, but it flickers when opening. The StoryBoard version is smoother and does not flicker.

**Comment by MichaelPetrinolis** [comment]
Hi @jerrynixon , any suggestions?

**Comment by JerryNixon** [comment]
Re-templating this at this level will be trouble when it is updated internally. But is good now.

**Pull request merged**
