### PR TITLE
Added readme.md & logo

### PR DESCRIPTION
**Pull request by RonanCodes**
Added readme.md & logo

### CODE REVIEW

**Comment by zangai** [comment]
Good start! :+1:

**Comment by RonanCodes** [comment]
Thanks, would be good to have some basic information for beginners.
Also a nice logo always makes things look better :)

**Comment by RonanCodes** [comment]
:-1: 
Sad times.

**Comment by JerryNixon** [comment]
Having Git issues. Not issues with you. Sorry. Pull request the readme again. Not the logo. Wanting to use the attached logos. :) // Jerry

**Comment by JerryNixon** [comment]
Edit this instead: https://github.com/Windows-XAML/Template10/wiki

**Pull request closed without merging**
