### PR TITLE
Page header sample Fix

### PR DESCRIPTION
**Pull request by artfuldev**
[A commit](https://github.com/Windows-XAML/Template10/commit/1d275270a8d6db54b4a9e5b82da1423d8e1128ca#diff-8bbb2d0d4796bc83bf559387de4db2e4) from #424 broke the sample, because Shell was constructed using NavigationService created from NavigationServiceFactory. Whereas now the NavigationServiceFactory returns an INavigationService, the Shell constructor expects a NavigationService. So changed constructor of shell to expect INavigationService instead.

### CODE REVIEW

**Comment by artfuldev** [comment]
Actually how to remove this behavior commit from this?
I made it on the master branch and it's ruining everything for me. Any help?

**Comment by schuettecarsten** [comment]
Take a look at my additional changes in https://github.com/Windows-XAML/Template10/pull/449. Normally changing NavigationService to INavigationService should be enough. If this does not help on your existing code, I need more details.

**Comment by artfuldev** [comment]
Changing NavigationService to INavigationService is all that's needed to make it work and that's all I've done. :) The first commit is something I'm trying to remove.

**Comment by artfuldev** [comment]
Actually I have made too many commits for a small change and I am unable to rebase or squash. Also the original author has submitted another pull request #455 which also fixed this so I'm closing this pull request.

**Pull request closed without merging**
