### PR TITLE
Update Hamburger Menu controls to support swipe to show on Narrow Status

### PR DESCRIPTION
**Pull request by lyling**

### CODE REVIEW

**Comment by JerryNixon** [comment]
Is this really a good idea? won't it get in the way of controls mistakenly placed UNDER this rectangle?

**Comment by JerryNixon** [comment]
Did you remember that the menu could be on the Right?

**Comment by lyling** [comment]
Yes. It may happen.  i will implement it using customize splitview to do it.

any suggestion from you?

**Comment by JerryNixon** [comment]
Just not convinced this is a good idea. Is it?

**Comment by darenm** [comment]
Are there risks that it could swallow interaction activities destined for the content area? Drag and drop, swipe to change pivot, etc.?

**Comment by lyling** [comment]
please reject this pull request , I will implement it by other solution , customize splitview .

**Pull request closed without merging**
