### PR TITLE
Tidy up samples

### PR DESCRIPTION
**Pull request by rcbevans**
Remove any unused references, name samples in a consistent way: `T10 <Sample Name> Sample`.  Update Behaviors to 1.1.0, and Newtonsoft.Json to 8.0.3.  Fix any broken samples, ensure they all run, same for template projects blank, hamburger, minimal.

### CODE REVIEW

**Comment by rcbevans** [comment]
@JerryNixon no real changes here, just cleaning up the solution, naming samples in a nicer way, removing unused references from projects, and fixed a couple of the samples which weren't building.

samples in menu

**Comment by JerryNixon** [comment]
So, re-base this for me. Then email me straight away. With this many files changes, I'll likely create conflicts fast, an email from you will help me review it right away. I like these changes, by the way. 
jnixon at microsoft.com is my email address.

**Comment by artfuldev** [comment]
Actually this is crashing chrome when i try to check the commits page. How about we tidy up a project at a time. Will also be easy to review and merge.

**Comment by JerryNixon** [comment]
Yeah. Good point. This is a good move, for sure.

**Comment by artfuldev** [comment]
We could also use `Template10.Samples.<SampleName>Sample` as the default namespace.

**Comment by artfuldev** [comment]
Also, I think there are some problems with using Behaviors 1.1.0 with T10. See https://github.com/Windows-XAML/Template10/commit/e0be81c82f9c35b9091e075ba874612df17c0bb0
We should be careful.

**Comment by rcbevans** [comment]
@artfuldev I had seen that commit, but I didn't see any comments of explanations as to why this was rolled back.  I can definitely go and roll it all back to 1.0.3 if there is a justification that I had missed somewhere that you can point me to.

@artfuldev I think the namespace change is a good Idea, so I'll make the change when I'm rebasing.

@JerryNixon I'll rebase and drop you an email to let you know ASAP so we can get the pull it without ruining anyones weekend :laughing:

**Comment by rcbevans** [comment]
Rebased, updated namespaces and removed unnecessary usings

**Comment by rcbevans** [comment]
Also, @artfuldev "Actually this is crashing chrome when i try to check the commits page"

You should use edge, no crashes :laughing:

**Comment by artfuldev** [comment]
Nice :+1:

PS: I do use Edge, will try GitHub on it too. There are just too many useful extensions for GitHub that I use on Chrome to instantly make the switch and feel at home. Maybe for huge commits like yours I will use Edge henceforth. ;)

**Comment by JerryNixon** [comment]
Why did you have to mess around with the Templates?! Read the TITLE of your PR.

**Comment by JerryNixon** [comment]
I still want to do this, by the way. Definitely.

**Comment by rcbevans** [comment]
@JerryNixon what's the issue, if there are any hunks you want reversing let me know and I'll update the PR.  Is it the renaming of something, or the project.json?  You'll have to clarify so I can fix it

**Comment by JerryNixon** [comment]
Okay, let's update only the Samples and not the Templates.  They are... delicate :)

**Comment by rcbevans** [comment]
Reverted all changes to the Templates (Project)/\* directory, do you want to check it again @JerryNixon

**Pull request merged**
