### PR TITLE
Bugfix/back button crash

### PR DESCRIPTION
**Pull request by bc3tech**

### CODE REVIEW

**Comment by bc3tech** [comment]
@JerryNixon found the root cause. The `args.handled=true` _every time_ `BackRequested` fires is the error. in the case where we're at top level, we won't actually end up handling anything, so we should let the OS take care of it... right?

**Comment by JerryNixon** [comment]
Ah, yeah. So consider that it is common for an app to have more than one Frame. That means more than one NavService. The library already supports this. What do you suggest?

**Comment by bc3tech** [comment]
Multiple frames = multi window app on "non-mobile" device family, right?

**Comment by tibitoth** [comment]
@bc3tech Not only. In Jerry's SplitView pattern there are multiply Frames in phones too.

**Comment by bc3tech** [comment]
haven't looked at this. is it possible on, say, a phone?

**Comment by tibitoth** [comment]
Oh sorry, there aren't two Frames in Jerrys SplitView samle but it is possible to use one Frame outside the SplitView and one inside the SplitView. http://blog.jerrynixon.com/2015/04/implementing-hamburger-button-with.html

**Comment by bc3tech** [comment]
Here's my (theoretical) thinking:
`BackPressed` should only set `handled = true` if it does actually handle something.
That being said, it's the developer's job for handling the behavior if & when it makes sense to do so. So, for the case of multiple frames I had better, as a developer, handle what the back button means for my frame (as in the split view, to collapse it) and therefore set `handled = true` when I do.
For multi-window applications, I think the "fix" shown in this PR is still valid. On desktop, multi window app have their own Back (when possible) button and a **close** button for when the user can no longer go back. For mobile apps, we don't really have the concept of multi-window, so hitting back in a new window until you're at the top of the stack should (and will, I believe) close that secondary window and take you back to the main app.

Admittedly I've not worked with multi-frame/window UWPs yet.

**Pull request closed without merging**
